# Generated by Django 5.0.6 on 2024-07-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_app", "0002_task_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completion_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
