# Generated by Django 5.0.6 on 2024-07-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_app", "0004_shopitem_userprofile_daily_task_limit_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="task_limit_increases",
            field=models.IntegerField(default=0),
        ),
    ]
