# Generated by Django 5.0.6 on 2024-07-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_app", "0005_userprofile_task_limit_increases"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="all_time_gems",
            field=models.IntegerField(default=0),
        ),
    ]
